# Generated by Django 3.1.2 on 2021-03-07 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField(default=1)),
                ('posttitle', models.CharField(default='کارشناس', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=255)),
                ('lastname', models.CharField(db_column='lastname', max_length=255)),
                ('post', models.CharField(db_column='post', max_length=255)),
                ('year', models.IntegerField(db_column='year', default=1399)),
                ('month', models.IntegerField(db_column='month', default=1)),
                ('day', models.IntegerField(db_column='day', default=1)),
                ('tell', models.IntegerField(blank=True, db_column='tell')),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='pictures/')),
                ('postid', models.IntegerField(db_column='postid', default=1)),
                ('Email', models.CharField(db_column='Email', max_length=255, null=True)),
                ('managerid', models.IntegerField(db_column='managerid', null=True)),
                ('username', models.ForeignKey(db_column='username', max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'lotus_cooperators_employee',
                'permissions': [('is_manager', 'Can see employee'), ('is_employee', 'Can see self')],
            },
        ),
    ]
