# Generated by Django 3.1.2 on 2021-04-27 05:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus_cooperators', '0002_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, default=0, max_length=31),
        ),
    ]
