# Generated by Django 3.1.2 on 2021-06-12 03:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus_cooperators', '0003_auto_20210427_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
