# Generated by Django 3.1.2 on 2021-06-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus_cooperators', '0005_employee_employmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='day',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='month',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year',
        ),
    ]
